### ISSUE TITLE
Description Text Hover

### ISSUE THREAD

**Issue by PhilipLeddin** [sprinteins/oscd-plugin-store#18]
As a user I want to see the whole description text when hovering the description.

ACs:

- [ ] the hover should only appear when there is more text then in two rows displayed
- [ ] the whole description text will be displayed as a hover hint when hovering it
- [ ] use similar hover behaviour like in other OpenSCD hovers

**Comment by rdsov** [comment]
<img width="955" alt="Tooltip" src="https://github.com/user-attachments/assets/22b7d0d4-8bfa-492e-95e6-59a1debb7f18">
